#!/bin/bash

case "$1" in
	power)
		charging=`cat /sys/class/power_supply/AC0/online`
		level=`cat /sys/class/power_supply/BAT0/capacity`

		echo $([[ $charging = 1 ]] && echo '' || echo '') ${level}%
		;;

	music)
		maxlen="54";
		if [ ! -e /tmp/pbarinfomusicscroll ]; then
			echo '0' > /tmp/pbarinfomusicscroll;
		fi
		if [[ `mpc status | tail -n2 | head -n1 | awk '{print $1}'` = "[playing]" ]]; then
			ret=`mpc current`
		else if [[ `playerctl status 2>/dev/null` = 'Playing' ]]; then
				ret="[`playerctl metadata artist`] - `playerctl metadata title`"
			else
				ret="No song playing"
			fi
		fi
		scroll=`cat /tmp/pbarinfomusicscroll`
		scrolllimit=$(( ${#ret}-maxlen+1 ))
		(( scrolllimit < 1 )) && scrolllimit=1
		echo $(( (scroll+1) % scrolllimit )) > /tmp/pbarinfomusicscroll;
		# echo "0" > /tmp/pbarinfomusicscroll;
		# echo $maxlen
		echo "$maxlen $scroll $ret" | awk '{print substr($0, length($1)+length($2)+3+$2, $1)}'
		;;

	ram)
		free | grep 'Mem' | awk '{printf "RAM %3.0f%%", $3/$2*100}'
		;;

	disk)
		df -h | grep '/$' | awk '{printf " %s", $4}'
		;;

	cpu)
		watts=`cat /sys/class/power_supply/BAT0/power_now | awk '{printf "%04.1f", $1/1000000}'`W
		temp=`cat /sys/class/thermal/thermal_zone0/temp | awk '{printf "%02.0f", $1/1000}'`°C
		echo $watts $temp
		;;

	*)
		echo "Invalid or missing input"
		;;
esac